name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: treeform/setup-nim-action@v6
      - run: sudo apt-get update && sudo apt-get install -y libudev-dev libevdev-dev
        if: matrix.os == 'ubuntu-latest'
      - run: nimby install -g
      - run: nim check src/paddy.nim
      - run: nim r tests/tests.nim
